[module]
[[module.imports]]
path="github.com/twbs/bootstrap"
[[module.imports.mounts]]
source = "scss"
target = "assets/sass/bootstrap"
[[module.imports.mounts]]
source = "dist/js"
target = "assets/js/bootstrap"

[[module.imports]]
path="github.com/thomaspark/bootswatch"
[[module.imports.mounts]]
source = "dist"
target = "assets/sass/bootswatch"

[[module.imports]]
path="github.com/googlefonts/NunitoSans"
[[module.imports.mounts]]
source = "fonts/ttf"
target = "assets/fonts/nunitosans"

[mediaTypes]
[mediaTypes."application/x-php"]
suffixes = ['php']

[outputFormats]
[outputFormats.PHP]
mediaType = "application/x-php"
isPlainText = true
permalinkable = true
noUgly = true

[params]
scssOutputStyle = "compressed"
scssEnableSourceMap = true
